"""empty message

Revision ID: d430fc49fdd3
Revises: 
Create Date: 2024-11-28 13:24:54.507721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd430fc49fdd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_price_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate_code', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=15), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('offer_code', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=True),
    sa.Column('cpus', sa.Integer(), nullable=True),
    sa.Column('clock_speed', sa.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('ram', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('price_per_unit', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('price_description', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('instance_type', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('instance_family', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_code'),
    sa.UniqueConstraint('rate_code', 'region_code', name='rate_code_region_code_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_price_data')
    # ### end Alembic commands ###
